#=================================================================================================#
# CONFIG FOR RVILLAGERWAND
#=================================================================================================#

#Plugin message prefix
Prefix: "&e[&9rVillagerWand&e] &b"

#Title for Villager wand menu
Menu_title: "&c&lWand Menu"

#Ability to trade with Villagers unlimited amount of times
Unlimitade_trades: false

WAND:

  #The name of the wand
  Name: "&cVillager Wand"

  #When using /wand and the item the player is holding is incorrect
  #Use {wand} to get the item the wand should be made of
  Wrong_item_message: "&eOnly a &a{wand} &ecan be made into a wand"

  #Set what item to use as a wand
  Item: STICK

  #Set instructions on the wand
  Lore:
    - "&fAttack to cast spells"
    - "&fUse to open the menu"

  #How to display the cost of using a spell
  #Use {item} to get the item name
  #use {cost} to get amount of item needed
  Cost_display:
    - "&eCost: &a{cost} {item}"

PERMISSION:

  #Send player a message if they do not have the required permission to use a spell
  Show_message: true

  #Error message to player when trying to use a wand the player doesn"t have the required permission to use
  Message: "&cYou do not have the required permission to use this wand"

NOTENOUGHITEMS:

  #Send player a message if the player does not have enough items to use the spell
  Show_message: true

  #Message to send to player if they don"t have enough items to use the spell
  Message: "&cYou do not have enough items in your inventory to use this spell"


#Allow a villager to infinitely replenish its trades
Allow_infinite_trades: true


#=================================================================================================#
# DROP INVENTORY
#=================================================================================================#
DROP:

  #Wand name
  Name: "&b&lDrop Inventory"

  #What item to use in the menu
  Icon: HOPPER

  #Additional information to display on the wand
  Lore:
    - "&aVillager will drop its inventory"

  #If villager has any item in its inventory
  Message: ""

  #If Villager doesn't have any item in its inventory
  Empty_inventory_message: "&eInventory is already empty"

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item:

  #Amount of material it cost
  Amount:

  #Allow Villagers to drop there inventory when killed by the wand
  Enable: true

#=================================================================================================#
# FOLLOW
#=================================================================================================#
FOLLOW:

  #Wand name
  Name: "&b&lToggle follow"

  #What item to use in the menu
  Icon: LEAD

  #Additional information to display on the wand
  Lore:
    - "&aToggle if selected Villager will follow you"

  #Villager start follow message
  Start_message: "This Villager will try to follow {player}"

  #Villager stop follow message
  Stop_message: "This Villager will not follow you anymore"

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item:

  #Amount of material it cost
  Amount:

#=================================================================================================#
# GET HP
#=================================================================================================#
GETHP: #Use {hp} to get Villager's hp

  #Wand name
  Name: "&b&lGet HP"

  #What item to use in the menu
  Icon: RED_WOOL

  #Additional information to display on the wand
  Lore:
    - "&aGets the Villager's HP"

  #Message when checking hp
  Message: "&3This Villager's HP is: &a{hp}"

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item:

  #Amount of material it cost
  Amount:

#=================================================================================================#
# GIVE EXP
#=================================================================================================#
GIVEEXP:

  #Wand name
  Name: "&b&lGive EXP"

  #What item to use in the menu
  Icon: EXPERIENCE_BOTTLE

  #Additional information to display on the wand
  Lore:
    - "&aGives Villager exp"

  #Use {exp} to get Villager's experience total
  #Message when exp was given to villager
  GiveEXP_message: "{exp}"

  #Message when the Villager is the highest level
  HighestEXP_message: "This Villager already has enough exp for the highest level"

  #Message when the Villager is the highest level
  No_proffesion_message: "The Villager needs to have a profession"

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item: EXPERIENCE_BOTTLE

  #Amount of material it cost
  Amount: 1

  #Amount of exp to give
  EXP: 7

#=================================================================================================#
# GLOW
#=================================================================================================#
GLOW:

  #Wand name
  Name: "&b&lToggle glow"

  #What item to use in the menu
  Icon: GLOWSTONE

  #Additional information to display on the wand
  Lore:
    - "&aToggle if Villager should glow"

  #Message when glow effect is applied
  Start_message: ""

  #Message when glow effect is removed
  Stop_message: ""

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item:

  #Amount of material it cost
  Amount:

#=================================================================================================#
# HEAL
#=================================================================================================#
HEAL:

  #Wand name
  Name: "&b&lHeal"

  #What item to use in the menu
  Icon: BREAD

  #Additional information to display on the wand
  Lore:
    - "&aFully heal the Villager"

  #When the villager has been fully healed
  Healed_message: "&aThis Villager has been healed"

  #If villager already is fully healed
  Already_full_health_message: "&eThis Villager is already fully &ahealed"

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item: BREAD

  #Amount of material it cost
  Amount: 1

#=================================================================================================#
# KILL
#=================================================================================================#
KILL:

  #Wand name
  Name: "&b&lKill"

  #What item to use in the menu
  Icon: LAVA_BUCKET

  #Additional information to display on the wand
  Lore:
    - "&cKills the Villager"
    - "&aWithout making any other Villager mad"

  #If this spell should drop Villager's inventory on the ground
  Drop: true

  #When villager is killed
  Message: "&cThat poor Villager didn't stand a chance"

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item:

  #Amount of material it cost
  Amount:

#=================================================================================================#
# NEW TRADE
#=================================================================================================#
NEWTRADES:

  #Wand name
  Name: "&b&lNew trades"

  #What item to use in the menu
  Icon: WRITABLE_BOOK

  #Additional information to display on the wand
  Lore:
    - "&eReset Villager's trades"
    - "&4Only works if the Villager has never traded"
    - "&eHold enchanted book in offhand and the Villager"
    - "&ewill try to make you an offer for that book"

  #If true only allow Success_message when a Villager is offering an enchanted book
  Only_show_enchanted_books: false

  #Message to display the new items the Villager has to offer, use {item} {price}
  Success_message: "&eNow offering &3{item} &efor &a{price}"

  #Message if Villager has a profession and has not been traded with
  Fail_message: "&cThis spell only works if the Villager has a profession and has not been traded with!"

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item:

  #Amount of material it cost
  Amount:

#=================================================================================================#
# PICK UP
#=================================================================================================#
PICKUP:

  #Wand name
  Name: "&b&lPick up"

  #What item to use in the menu
  Icon: VILLAGER_SPAWN_EGG

  #Additional information to display on the wand
  Lore:
    - "&eTurns Villager into a spawn egg"

  #Message when villager is turned into a spawn egg
  Message: ""

  #Message when villager is not an adult
  Not_adult_message: "&cYou can only pick up adults"

  #Message if villager has a profession
  Has_profession_message: "&cYou can only pick up Villagers who doesn't have a profession"

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item:

  #Amount of material it cost
  Amount:

#=================================================================================================#
# AI
#=================================================================================================#
TOGGLEAI:

  #Wand name
  Name: "&b&lToggle AI"

  #What item to use in the menu
  Icon: ENCHANTED_BOOK

  #Additional information to display on the wand
  Lore:
    - "&5Toggle if Villager's &cAI&5 is on"

  #Message when AI is turned on
  On_message: ""

  #Message when AI is turned off
  Off_message: ""

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item:

  #Amount of material it cost
  Amount:

#=================================================================================================#
# AWARENESS
#=================================================================================================#
AWARE:

  #Wand name
  Name: "&b&lToggle awareness"

  #What item to use in the menu
  Icon: CARVED_PUMPKIN

  #Additional information to display on the wand
  Lore:
    - "&5Toggle if Villager's &cawareness&5 is on"
    - "No awareness means Villager will no move on its own"

  #Message when awareness is turned on
  On_message: "&eThis villager's awareness is turned &aon"

  #Message when awareness is turned off
  Off_message: "&eThis villager's awareness is turned &coff"

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item:

  #Amount of material it cost
  Amount:

#=================================================================================================#
# INVISIBILITY
#=================================================================================================#
TOGGLEINVISIBILITY:

  #Wand name
  Name: "&b&lToggle invisibility"

  #What item to use in the menu
  Icon: GOLDEN_CARROT

  #Additional information to display on the wand
  Lore:
    - "&5Toggle if villager is &cinvisible"

  #Message when villager is set to invisible
  Is_invisible_message: ""

  #Message when villager is set to visible
  Is_visible_message: ""

  #If you want this option to show in the menu
  Show: true

  #Item cost to use this spell
  Item:

  #Amount of material it cost
  Amount:

#=================================================================================================#
# INVULNERABLE
#=================================================================================================#
TOGGLEINVULNERABLE:

  #Wand name
  Name: "&b&lToggle invulnerable"

  #What item to use in the menu
  Icon: BEDROCK

  #Additional information to display on the wand
  Lore:
    - "&5Toggle if Villager is &cinvulnerable"
    - "&cThis will stop the wand from working on this"
    - "&c Villager if you are playing in anything but creative"

  #Message when villager is set to invulnerable
  Invulnerable_message: ""

  #Message when villager is set to vulnerable
  Vulnerable_message: ""

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item:

  #Amount of material it cost
  Amount:

#=================================================================================================#
# PICK UP ITEMS
#=================================================================================================#
TOGGLEPICKUPITEMS:

  #Wand name
  Name: "&b&lToggle item pick up"

  #What item to use in the menu
  Icon: CHEST

  #Additional information to display on the wand
  Lore:
    - "&aToggle if Villager can pick up items"

  #Message when pick up is turned on
  Pickup_on_message: ""

  #Message when pick up is turned off
  Pickup_off_message: ""

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item:

  #Amount of material it cost
  Amount:

#=================================================================================================#
# SILENCE
#=================================================================================================#
TOGGLEMUTE:

  #Wand name
  Name: "&b&lToggle mute"

  #What item to use in the menu
  Icon: WHITE_WOOL

  #Additional information to display on the wand
  Lore:
    - "&5Toggle if Villager should be muted"

  #Message when villager is muted
  Muted_message: "&eVillager is now &cmuted"

  #Message when villager is unmuted
  Unmuted_message: "&eVillager is now &aunmuted"

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item:

  #Amount of material it cost
  Amount:

#=================================================================================================#
# CHANGE CLOTHES
#=================================================================================================#
TOGGLECLOTHES: #Use {type} to get villager type

  #Wand name
  Name: "&b&lChange clothes"

  #What item to use in the menu
  Icon: CHAINMAIL_CHESTPLATE

  #Additional information to display on the wand
  Lore:
    - "&5Change the Villager's clothes"

  #Message when changing clothes
  #Use {type} to get the new Villager type
  Message: ""

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item:

  #Amount of material it cost
  Amount:

#=================================================================================================#
# TOGGLE PROFESSION
#=================================================================================================#
TOGGLEPROFESSION: #Use {type} to get villager type

  #Wand name
  Name: "&b&lChange profession"

  #What item to use in the menu
  Icon: BOOK

  #Additional information to display on the wand
  Lore:
    - "&5Change the Villager's profession"
    - "&5Only works if Villager has a"
    - "&5workstation"

  #Message when changing clothes
  #Use {type} to get the new Villager type
  Message: ""

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item:

  #Amount of material it cost
  Amount:

#=================================================================================================#
# UNEMPLOYMENT
#=================================================================================================#
UNEMPLOYMENT:

  #Wand name
  Name: "&b&lFire Villager"

  #What item to use in the menu
  Icon: CHAINMAIL_BOOTS

  #Additional information to display on the wand
  Lore:
    - "&cReset Villager to 0 exp"
    - "&cand remove profession"

  #Message when Villager is unemployed
  Success_message: "&aThis Villager is now unemployed"

  #Message when Villager has experience
  Failed_message: "&cThis Villager is already unemployed"

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item:

  #Amount of material it cost
  Amount:

#=================================================================================================#
# TURN ZOMBIFIED VILLAGER INTO VILLAGER
#=================================================================================================#
ZOMBIETOVILLAGER:

  #Wand name
  Name: "&b&lSave Zombified Villager"

  #What item to use in the menu
  Icon: GOLDEN_APPLE

  #Additional information to display on the wand
  Lore:
    - "&eTurns &cZombiefied Villager&e into &aVillager"

  #Message when converting a Zombiefied Villager into a Villager
  Message: ""

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item: GOLDEN_APPLE

  #Amount of material it cost
  Amount: 1

#=================================================================================================#
# TURN VILLAGER INTO ZOMBIFIED VILLAGER
#=================================================================================================#
VILLAGERTOZOMBIE:

  #Wand name
  Name: "&b&lZombifiy villager"

  #What item to use in the menu
  Icon: ZOMBIE_HEAD

  #Additional information to display on the wand
  Lore:
    - "&eTurns &aVillager &einto a &cZombiefied Villager"

  #Message when converting a villager into a Zombiefied Villager
  Success_message: ""

  #Message if Villager isn't an adult
  Fail_message: "&cYou can only turn adult Villagers into a Zombified Villager"

  #If you want this option to show in the menu
  Show: true

  #Item to pay with for using this spell
  Item: ROTTEN_FLESH

  #Amount of material it cost
  Amount: 1

#=================================================================================================#
# ITEM/CHAT FORMAT (CHEAT SHEET)
#=================================================================================================#

# CHATCOLOR CODES
# &0 Black
# &1 Dark Blue
# &2 Dark Green
# &3 Dark Aqua
# &4 Dark Red
# &5 Dark Purple
# &6 Gold
# &7 Gray
# &8 Dark Gray
# &9 Blue
# &a Green
# &b Aqua
# &c Red
# &d Light Purple
# &e Yellow
# &f White

###############################################################
#IF USING THESE MAKE SURE TO USE ALWAYS USE COLOR BEFORE
# THIS WORKS &b&l
# THIS DOES NOT WORK &l&b
###############################################################
# &k Obfuscated
# &l Bold
# &m Strikethrough
# &n Underline
# &o Italic
# &r Reset the default color

